[package]
name = "muxwm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
i3ipc = "0.10.1"
rusqlite = { version = "0.38.0", features = ["bundled"] }
